# Generated by Django 2.2 on 2022-09-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder__app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_item',
            field=models.ManyToManyField(related_name='sold_items', to='boarder__app.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='traded_item',
            field=models.ManyToManyField(related_name='treaded_items', to='boarder__app.User'),
        ),
    ]
