# Generated by Django 2.2 on 2022-09-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder__app', '0002_auto_20220918_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
