# Generated by Django 2.2 on 2022-09-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boarder__app', '0004_auto_20220928_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
    ]
