# Generated by Django 2.2 on 2022-10-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boarder__app', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='added_item',
        ),
    ]
