# Generated by Django 2.2 on 2022-10-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder__app', '0009_remove_item_added_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='traded_item',
            field=models.ManyToManyField(related_name='traded_items', to='boarder__app.User'),
        ),
    ]
